"""
deep_q_sp_bid() SQL Query Rewrite
==================================
Original query from deep_q_24.py (lines 2136-2236)
Modified to add 3 new columns:
    1. TOS_LAST_HOUR_IMP  - Top of Search impressions in the last hour
    2. PP_LAST_HOUR_IMP   - Product Page impressions in the last hour
    3. ROS_LAST_HOUR_IMP  - Rest of Search impressions in the last hour

Changes from original:
    - Added LAST_HOUR_IMP_TAB CTE: gets impressions per KEYWORD per PLACEMENT
      from the last 1 hour (using TIME_WINDOW_START, not TIMESTAMP)
    - Added LAST_HOUR_PIVOT_TAB CTE: pivots placement rows into 3 columns per keyword
    - Joined LAST_HOUR_PIVOT_TAB into FINAL_TAB via LEFT JOIN on KEYWORDID
    - Added TOS_LAST_HOUR_IMP, PP_LAST_HOUR_IMP, ROS_LAST_HOUR_IMP to FINAL_TAB SELECT
"""

sp_bid_query = f"""
--FOR SP BID (REWRITE - 3 NEW COLUMNS ADDED)
DECLARE @NOW DATETIME = '{{now}}',
	@INTERVAL INT = {{interval}},
	@MONITOR BIT = {{monitor}};
DECLARE @STARTOFHOUR DATETIME2 = CAST(FORMAT(@NOW, 'yyyy-MM-dd HH:00') AS DATETIME2);
DECLARE @CVRDAYCOUNT INT = (SELECT MAX(CVRDAYCOUNT) FROM MODELING_DB.DBO.Q_MASTER
    WHERE DEEPQSWITCH = 1 AND CAMPAIGNTYPE IN ('SP'));

WITH MAIN_TAB AS (
    SELECT * FROM MODELING_DB.DBO.Q_MASTER
    WHERE DEEPQSWITCH = 1 AND CAMPAIGNTYPE IN ('SP')),
KEY_TAB AS (
        SELECT * FROM MODELING_DB.DBO.KEYWORDS_FOR_AGENT
        WHERE CAMPAIGNID IN (SELECT CAMPAIGNID FROM MAIN_TAB)),
SQS_TAB AS(
	SELECT CAMPAIGN_ID, KEYWORD_ID, PLACEMENT, CLICKS, IMPRESSIONS, COST, [TIMESTAMP]
	FROM [AMAZON_MARKETING].[DBO].AS_SP_TRAFFIC
	WHERE CAST(TIME_WINDOW_START AS DATE) = CAST(@NOW AS DATE)
		 AND CAMPAIGN_ID IN (SELECT CAMPAIGNID FROM MAIN_TAB)),
CURR_TAB AS (
    SELECT KEYWORD_ID, SUM(CLICKS) CLK0, SUM(IMPRESSIONS) IMP0, SUM(COST) COST0,
		CASE WHEN SUM(CLICKS) = 0 THEN 0 ELSE CAST(SUM(COST) AS FLOAT)/SUM(CLICKS) END AS CPC,
        CASE WHEN SUM(IMPRESSIONS) = 0 THEN 0 WHEN SUM(IMPRESSIONS) > 0 AND SUM(CLICKS) <= 0 THEN (1.0/SUM(IMPRESSIONS) - 1)
        ELSE CAST(SUM(CLICKS) AS FLOAT)/SUM(IMPRESSIONS) END AS CTR0
    FROM SQS_TAB GROUP BY KEYWORD_ID),
PREV_TAB AS (
    SELECT KEYWORD_ID, SUM(CLICKS) CLK1, SUM(IMPRESSIONS) IMP1,
		CASE WHEN SUM(CLICKS) = 0 THEN 0 ELSE CAST(SUM(COST) AS FLOAT)/SUM(CLICKS) END AS CPC1,
        CASE WHEN SUM(IMPRESSIONS) = 0 THEN 0 WHEN SUM(IMPRESSIONS) > 0 AND SUM(CLICKS) <= 0 THEN (1.0/SUM(IMPRESSIONS) - 1)
		ELSE CAST(SUM(CLICKS) AS FLOAT)/SUM(IMPRESSIONS) END AS CTR1
    FROM SQS_TAB WHERE [TIMESTAMP] <= DATEADD(MINUTE, -@INTERVAL, @NOW)
    GROUP BY KEYWORD_ID),
TOTAL_CLICK_TAB AS (
	SELECT KEYWORD_ID, SUM(CLICKS) AS CLICKS FROM [AMAZON_MARKETING].[DBO].AS_SP_TRAFFIC
	WHERE CAST(TIME_WINDOW_START AS DATETIME2) >= DATEADD(HOUR, -@CVRDAYCOUNT, @NOW) AND CAST(TIMESTAMP AS DATE) <= @NOW
	GROUP BY KEYWORD_ID),
TOTAL_CONV_TAB AS (
	SELECT KEYWORD_ID, SUM(CONVERSIONS_14D) AS CONVERSION FROM [AMAZON_MARKETING].[DBO].AS_SP_CONVERSION
	WHERE CAST(TIME_WINDOW_START AS DATETIME2) >= DATEADD(HOUR, -@CVRDAYCOUNT, @NOW) AND CAST(TIMESTAMP AS DATE) <= @NOW
	GROUP BY KEYWORD_ID),
CONV_TAB AS (
		SELECT SUM(CONVERSION) AS UNITS
		FROM (
			SELECT ISNULL(ORDERCOUNT - LAG(ORDERCOUNT) OVER (PARTITION BY CAST(TIMESTAMP AS DATE) ORDER BY TIMESTAMP), 0) AS CONVERSION
			FROM [AMAZON_MARKETING].[DBO].[AMZN_SALES_DATA]
			WHERE TIMESTAMP >= DATEADD(HOUR, -1, @STARTOFHOUR)
			  AND TIMESTAMP <= @NOW
		) AS TAB),
LATEST_CPC_TAB AS (
	SELECT KEYWORD_ID, MAX([TIMESTAMP]) LATEST
	FROM SQS_TAB WHERE COST > 0 GROUP BY KEYWORD_ID),
CPC_CURR_TAB AS(
	SELECT ST.KEYWORD_ID, SUM(CAST(ST.COST AS FLOAT)) / SUM(ST.CLICKS) AS CPC FROM
	SQS_TAB ST JOIN LATEST_CPC_TAB LCT ON ST.KEYWORD_ID = LCT.KEYWORD_ID AND ST.[TIMESTAMP] = LCT.LATEST AND ST.CLICKS > 0
	GROUP BY ST.KEYWORD_ID),
CPC_PREV_TAB AS(
	SELECT ST.KEYWORD_ID, SUM(CAST(ST.COST AS FLOAT)) / SUM(ST.CLICKS) AS CPC FROM
	SQS_TAB ST JOIN(
		SELECT ST.KEYWORD_ID, MAX(ST.[TIMESTAMP]) PREV
		FROM SQS_TAB ST JOIN LATEST_CPC_TAB LCT
			ON ST.KEYWORD_ID=LCT.KEYWORD_ID AND ST.[TIMESTAMP] < LCT.LATEST AND ST.CLICKS > 0
		GROUP BY ST.KEYWORD_ID
	) PCT ON ST.KEYWORD_ID = PCT.KEYWORD_ID AND ST.[TIMESTAMP] = PCT.PREV AND ST.CLICKS > 0
	GROUP BY ST.KEYWORD_ID),
COST_TAB AS (
	SELECT CAMPAIGN_ID, SUM(CAST(COST AS FLOAT)) COST FROM SQS_TAB GROUP BY CAMPAIGN_ID),
KEY_CONV_TAB AS (
	SELECT KEYWORD_ID, SUM(CONVERSIONS_14D) AS CONV FROM [AMAZON_MARKETING].[DBO].AS_SP_CONVERSION
	WHERE CAST(TIME_WINDOW_START AS DATE) = CAST(@NOW AS DATE) AND [TIMESTAMP] <= @NOW
		AND CAMPAIGN_ID IN (SELECT CAMPAIGNID FROM MAIN_TAB)
	GROUP BY KEYWORD_ID),
PREV_KEY_CONV_TAB AS (
	SELECT KEYWORD_ID, SUM(CONVERSIONS_14D) AS PREV_CONV FROM [AMAZON_MARKETING].[DBO].AS_SP_CONVERSION
	WHERE CAST(TIME_WINDOW_START AS DATE) = CAST(@NOW AS DATE) AND [TIMESTAMP] <= DATEADD(MINUTE, -@INTERVAL, @NOW)
		AND CAMPAIGN_ID IN (SELECT CAMPAIGNID FROM MAIN_TAB)
	GROUP BY KEYWORD_ID),

-- ============================================================
-- NEW CTE: Last hour impressions per KEYWORD per PLACEMENT
-- Uses TIME_WINDOW_START (factory time = when impressions actually happened)
-- ============================================================
LAST_HOUR_IMP_TAB AS (
	SELECT KEYWORD_ID, PLACEMENT, SUM(IMPRESSIONS) AS LAST_HOUR_IMP
	FROM [AMAZON_MARKETING].[DBO].AS_SP_TRAFFIC
	WHERE CAST(TIME_WINDOW_START AS DATETIME2) BETWEEN DATEADD(HOUR, -1, @NOW) AND @NOW
		AND CAMPAIGN_ID IN (SELECT CAMPAIGNID FROM MAIN_TAB)
	GROUP BY KEYWORD_ID, PLACEMENT),

-- ============================================================
-- NEW CTE: Pivot placement rows into 3 columns per keyword
-- Same pattern as how SPT query pivots in MERGED_TAB
-- ============================================================
LAST_HOUR_PIVOT_TAB AS (
	SELECT KEYWORD_ID,
		ISNULL(SUM(CASE WHEN UPPER(PLACEMENT) = 'TOP OF SEARCH ON-AMAZON' THEN LAST_HOUR_IMP END), 0) AS TOS_LAST_HOUR_IMP,
		ISNULL(SUM(CASE WHEN UPPER(PLACEMENT) = 'DETAIL PAGE ON-AMAZON' THEN LAST_HOUR_IMP END), 0) AS PP_LAST_HOUR_IMP,
		ISNULL(SUM(CASE WHEN UPPER(PLACEMENT) = 'OTHER ON-AMAZON' THEN LAST_HOUR_IMP END), 0) AS ROS_LAST_HOUR_IMP
	FROM LAST_HOUR_IMP_TAB
	GROUP BY KEYWORD_ID),

FINAL_TAB AS (
	SELECT KT.KEYWORDID, KT.CAMPAIGNID, KT.ADGROUPID, MT.GAMMA, MT.LR, MT.EPSTART, MT.BASEBIDLOWER, MT.BASEBIDUPPER, MT.COMBINEDDEEPQSWITCH,
		MT.CVRFLAG, MT.CLICKSTEP, CASE WHEN TCV.CONVERSION>0 THEN CAST (TCLK.CLICKS AS FLOAT) / TCV.CONVERSION ELSE 0 END CVR,
        MT.CTRWEIGHT, MT.CONVWEIGHT, MT.CVRWEIGHT, MT.WEIGHTFLAG, MT.CPCWEIGHT, MT.BUDGETWEIGHT, MT.DYNAMICEXPLORE,
        MT.BOLTZFLAG, MT.TDECAY,
		ISNULL(ROUND(CT.CTR0,4),0) AS CURR_CTR, ROUND(ISNULL(CT.CTR0,0) - ISNULL(PT.CTR1,0),4) AS DELTA_CTR,
		ISNULL(ROUND(CT.CPC,2),0) AS CPC, ISNULL(ROUND(PT.CPC1,2),0) AS CPC1, ISNULL(CVT.UNITS,0) UNITS,
        ISNULL(CCT.CPC,0) CURR_CPC, ISNULL(CPT.CPC,0) PREV_CPC, ISNULL(CST.COST,0) SPENTBUDGET, ISNULL(KCT.CONV,0) CONV,
        ISNULL(PKCT.PREV_CONV,0) PREV_CONV, ISNULL(PT.CLK1,0) PREV_CLICK, ISNULL(CT.CLK0,0) CLICK, ISNULL(CT.COST0,0) COST,

		-- NEW: Last hour impressions per placement
		ISNULL(LHPT.TOS_LAST_HOUR_IMP, 0) AS TOS_LAST_HOUR_IMP,
		ISNULL(LHPT.PP_LAST_HOUR_IMP, 0) AS PP_LAST_HOUR_IMP,
		ISNULL(LHPT.ROS_LAST_HOUR_IMP, 0) AS ROS_LAST_HOUR_IMP

	FROM KEY_TAB KT LEFT JOIN CURR_TAB CT ON KT.KEYWORDID = CT.KEYWORD_ID
		LEFT JOIN MAIN_TAB MT ON KT.CAMPAIGNID = MT.CAMPAIGNID
		LEFT JOIN PREV_TAB PT ON KT.KEYWORDID = PT.KEYWORD_ID
		LEFT JOIN TOTAL_CLICK_TAB TCLK ON KT.KEYWORDID = TCLK.KEYWORD_ID
		LEFT JOIN TOTAL_CONV_TAB TCV ON KT.KEYWORDID = TCV.KEYWORD_ID
        LEFT JOIN CPC_CURR_TAB CCT ON KT.KEYWORDID = CCT.KEYWORD_ID
		LEFT JOIN CPC_PREV_TAB CPT ON KT.KEYWORDID = CPT.KEYWORD_ID
		LEFT JOIN COST_TAB CST ON KT.CAMPAIGNID = CST.CAMPAIGN_ID
		LEFT JOIN KEY_CONV_TAB KCT ON KT.KEYWORDID = KCT.KEYWORD_ID
		LEFT JOIN PREV_KEY_CONV_TAB PKCT ON KT.KEYWORDID = PKCT.KEYWORD_ID
        LEFT JOIN CONV_TAB CVT ON 1=1
		LEFT JOIN LAST_HOUR_PIVOT_TAB LHPT ON KT.KEYWORDID = LHPT.KEYWORD_ID)  -- NEW JOIN

SELECT * FROM FINAL_TAB
WHERE @MONITOR = 0 OR DELTA_CTR <= 0 --OR CPC <> CPC1
"""
